### ISSUE TITLE
add Red hat open source contest

### ISSUE THREAD

**Issue by nandini45** [anubhavsingh16/Open-Source-Events#11]
you can also add about it. I think it is similar to gsoc. it kickoffs in Feb
Open Source Contest is a competition for students during which we want to show students how easy it is to participate in open source projects. Students can also get feedback on their code and get it included in a real project. By participating in the Red Hat Open Source Contest students can win nice prizes.
link
https://research.redhat.com/red-hat-open-source-contest/

there is also one more contest i know about organised by codeblocks known as BOSS(bountiful open source programs)

**Comment by anubhavsingh16** [comment]
Thank You @nandini45 for the suggestion. I will definitely add both events in this repo.
Fell free to share with others, Thank You again👍
