### ISSUE TITLE
Following list can be included in the Open Source Events.

### ISSUE THREAD

**Issue by garimasingh128** [anubhavsingh16/Open-Source-Events#12]
Curated List of Open Source Programs, Events, and Competitions:

-Alibaba Summer of Code
-Bountiful Open Source Summer- BOSS
-ACM MM Open Source Software Competition
-NJACK Winter of Code
-OpenCode IIITA
-MDG Winter of Code
-BOSS - Bountiful Open Source Summer by Coding Blocks
-Microsoft Open Source Challenge

Thanks.

**Comment by anubhavsingh16** [comment]
Thank You @garimasingh128

**Comment by anubhavsingh16** [comment]
Hi, @garimasingh128 I just add some events from your list, please have a look. Remaining items for next time. Thank You @garimasingh128 Feel free to share with others.
Sharing information is also a contribution in open-source😇

**Comment by anubhavsingh16** [comment]
Thank You @garimasingh128, please have a look updated repo.
