### ISSUE TITLE
Add about Google Code In (GCI)

### ISSUE THREAD

**Issue by aryamanpuri** [anubhavsingh16/Open-Source-Events#2]
Google Code-in is a contest to introduce pre-university students (ages 13-17) to open source software development. 
Gather more information from https://codein.withgoogle.com

**Comment by anubhavsingh16** [comment]
Thanx @aryamanpuri

**Comment by anubhavsingh16** [comment]
Hey, @aryamanpuri Please have a look updated repo. Thanks for the suggestion.
Feel free to open a new issue or PR.😍
