### ISSUE TITLE
Add KWoC.

### ISSUE THREAD

**Issue by aashimgarg** [anubhavsingh16/Open-Source-Events#3]
Add details for KWoC for both student and mentor application.
@anubhavsingh16 your views.

**Comment by anubhavsingh16** [comment]
Yes and GSSoC is also not mentioned in the list

**Comment by anubhavsingh16** [comment]
Thanx aashim

**Comment by anubhavsingh16** [comment]
@aashimgarg Please have a look updated content is it ok now, if you want to edit any content so please open a PR for your changes.
Thank You.

**Comment by anubhavsingh16** [comment]
done
