### ISSUE TITLE
Should add Google Season of Docs

### ISSUE THREAD

**Issue by arteevraina** [anubhavsingh16/Open-Source-Events#7]
https://developers.google.com/season-of-docs

**Comment by anubhavsingh16** [comment]
Thank You @arteevraina

**Comment by anubhavsingh16** [comment]
Done, please have a look @arteevraina updated repo thank you for the suggestion.

**Comment by arteevraina** [comment]
@anubhavsingh16 Looks Good !! Thanks:)
