### ISSUE TITLE
Add I_Hack 

### ISSUE THREAD

**Issue by aashimgarg** [anubhavsingh16/Open-Source-Events#9]
Organised by Entrepreneurship Cell IIT Bombay is one of the preferred spots among engineering students who are willing to take up the challenge of coding for 48 hours. The incentives are both hardware and software along with a prize money of 1.5 lakh in both the categories.

**Comment by aashimgarg** [comment]
add if you want.

**Comment by anubhavsingh16** [comment]
ok thanks @aashimgarg

**Comment by anubhavsingh16** [comment]
Done @aashimgarg please have a look for confirmation.🥰
